name: Run tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Functional tests
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file ./docker/Dockerfile.tests
